name: Weekly Earthquake Update

on:
  schedule:
    - cron: '0 9 * * 1'  # every Monday at 09:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests google-cloud-bigquery

      - name: Set GCP credentials
        run: echo "${{ secrets.GCP_KEY_JSON }}" > key.json

      - name: Run earthquake script
        run: python earthquake_project.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json


