name: Hourly Earthquake Data Collection

on:
  schedule:
    - cron: '0 * * * *'  # runs at minute 0 of every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Earthquake-Data-Pipeline/requirements.txt

      - name: Set GCP credentials
        run: echo '${{ secrets.GCP_KEY_JSON }}' > key.json

      - name: Run earthquake script
        run: python Earthquake-Data-Pipeline/src/earthquake_project.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json



